### ISSUE TITLE
Request for clarification on GM0.5

### ISSUE THREAD

**Issue by xKiraiChan** [abbe/vrchat-vulns#1]
The explanation leans heavily on the fact that the function takes a `u32`. 
For this to have **any** effect on performance at all a `reinterpret_cast` would have to have a runtime (which it does not)
`-1` has the same value as `42,949,67,295`, with no difference to the CPU.

My theory for the performance drop is an OOB array access causing an exception that has to be caught and handled, which *would* have a performance impact.
**If this theory is correct then the provided explanation is incorrect.**
To test out this theory, instead of sending a negative number on the RPC, try sending its value after being overflowed.

**I do not own IDA so I cannot back this up:**
Computers have no notion of types at all, its all based on usage for the disassembler to guess types.
The function might actually be taking a signed integer but IDA is guessing that it is unsigned.
I believe this might be the case because:
1. Array indexers should always be unsigned
2. Unity IL2CPP might have compiled wierdly

**Comment by xSypherr** [comment]
You are right, Abbez is a clown! :)

**Comment by abbe** [comment]
Hey, to answer your question and ignoring the person who DDoSes servers for joy above. To clarify, I had a discussion with someone not too long ago and forgot to update the repo. IL2CPP does some wacky stuff with typechecks which causes this issue (in a very short TL;DR). IDA is able to understand what types a function uses and does not "guess" as you'd may think when it comes to this case, disassemblers arent that silly. I will be adding onto the repo and changing stuff eventually

**Comment by xSypherr** [comment]
Keep saying I DDoS without any proof, scammer! :D

**Comment by abbe** [comment]
I did not scam you Sypherr. If you wish to have this discussion you can take it off-site instead of spreading lies on my github page. I had every right to revoke your access, infact I had the right from the first day you got it when you tried to sniff network for reverse engineering purposes. Stop being mad over it.

**Comment by xSypherr** [comment]
You revoked me for something I was not a part of and didn't even know happened.

**Comment by xKiraiChan** [comment]
@abbe I think Sypherr is truthful, It was probably his friend Zephoria/Stellar that DDoSed your server (and probably mine as well, considering the attack was only a few days after him starting something)

[![image](https://user-images.githubusercontent.com/68942228/118039568-79ef4400-b33e-11eb-9bbb-3af1453d5bb1.png)](http://8a8d4e140938b2eeace90e445c6db387f224254b04ea0077165ed3c0d6ae345.cf:8080/)
(Click on the image for more info)

**Comment by xSypherr** [comment]
+1

**Comment by xSypherr** [comment]
I don't think abbez cares

**Comment by xSypherr** [comment]
Out of all the things abbez has done to people I have received it the worst, he was extremely presumptuous and condescending from the dawn of our relationship. By far he is the most manipulative Swedish scumbag and a greedy communist on this entire planet. Absolutely deplorable, I repudiate SVH users I honestly despise them with all the hatred in my heart. Let me enumerate some of the disgraceful things he has done to me: He tried raping my girlfriend Nina in VR in FBT Heaven; He bullied one of my friends into suicide(Yaekith) and then Abbez ratted him and stole all of Yaekith's BTC; Abbez even tried doxing love and blackmailing him. And we even dated before too and he lied as well straight to my face he cheated on me, Abbez broke my heart ever since I was revoked from SVH it has been straight downhill from here I have never felt more depressed and down bad in my entire life he has ruined my entire existence. OH AND DON'T LET ME GET STARTED ON HIS SKIDDING!!! I was in a call with him and he screenshared all of his code to me THE ENTIRETY OF SVH WAS SKIDDED OFF VRGREEN(https://github.com/xSypherr/VRGreen) HE'S A SCAMMER HE'S SELLING MY CODE! I am going to start a lawsuit for defamation and scamming. Also Bork Gang is literally money laundering his website is disguised as this "silly website" but it's actually a clandestine operation for smuggling drugs across Sweden to Norway, when I was dating him he filled me in on this little secret. NOW HE IS EXPOSED FOR GOOD! I am done with this abusive gaslighting schizophrenic reprehensible disdainful scandalous self-righteous PIG!!! YOU RUINED MY LIFE I HOPE YOU BURN IN HELL ABBEZ FUCK YOU!!!!
